import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";

export const Route = createFileRoute("/disclaimer")({
  component: DisclaimerPage,
  head: () => ({
    meta: [
      { title: "Disclaimer — PNX Free Agentic SEO Tool" },
      { name: "description", content: "PNX disclaimer: AI-generated SEO insights are guidance, not guarantees. Always validate with your own analytics." },
      { property: "og:title", content: "Disclaimer — PNX" },
      { property: "og:description", content: "PNX disclaimer — AI-generated SEO insights are guidance, not guarantees. Validate with your own analytics." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "https://pnx.lovable.app/disclaimer" },
    ],
    links: [{ rel: "canonical", href: "https://pnx.lovable.app/disclaimer" }],
  }),
});

function DisclaimerPage() {
  return (
    <div className="min-h-[100dvh] flex flex-col">
      <SiteHeader />
      <main className="mx-auto max-w-3xl px-4 py-12 prose prose-neutral dark:prose-invert">
        <h1>Disclaimer</h1>
        <p><em>Last updated: May 2026.</em></p>

        <h2>General</h2>
        <p>PNX provides AI-generated SEO insights for informational purposes. We make no guarantees about ranking improvements, traffic, or revenue.</p>

        <h2>No professional advice</h2>
        <p>PNX is not a substitute for professional SEO, legal, financial, or medical advice. Always validate critical decisions with qualified experts and your own analytics data.</p>

        <h2>Accuracy</h2>
        <p>AI models can hallucinate. Volume estimates, difficulty scores and competitive insights generated by PNX should be cross-checked before use.</p>

        <h2>Third-party content</h2>
        <p>PNX fetches publicly available web pages and SERP results. We are not responsible for the content of external sites.</p>

        <h2>Affiliate disclosure</h2>
        <p>Some outbound links on the blog may be affiliate links. We only link to tools we genuinely consider useful. This does not influence our editorial.</p>

        <h2>Ad disclosure</h2>
        <p>This site may display third-party ads (e.g. Google AdSense). Ads are clearly distinguishable from editorial content.</p>

        <h2>Contact</h2>
        <p><a href="mailto:saboortahir01@gmail.com">saboortahir01@gmail.com</a></p>
      </main>
      <SiteFooter />
    </div>
  );
}
